blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/jessy2027/AlphaCodeIDE/discussions
    about: Please ask and answer questions here.
  - name: Extension Development
    url: https://github.com/jessy2027/AlphaCodeIDE/discussions
    about: Please use this for extension development questions and ideas.
